### ISSUE TITLE
[QUESTION] Zoom hour-by-hour

### ISSUE THREAD

**Issue by mateusbays** [Bitnoise/react-scheduler#102]
Hello guys.

Actually, i saw on website an screenshot that shows the chart displaying an hour-by-hour. Anybody knows when it will be  released?
![image](https://github.com/Bitnoise/react-scheduler/assets/49691726/fdf9643f-e39b-44d0-ac67-63533e1b10f4)

**Comment by dmsolutionz** [comment]
I was thinking the same thing 👍 looking through the code in this repo the feature doesn't seem to exist. Maybe it was scrapped?

**Comment by ludakhris** [comment]
Or maybe it was just a mock up?

**Comment by mGasiorek998** [comment]
Hi, 

we're working on day view now, but we're definitely will add a hour view as well in the future :)
