### ISSUE TITLE
Issue with React Scheduler Overlaying Data from Different Years

### ISSUE THREAD

**Issue by davidluan** [Bitnoise/react-scheduler#106]
When my data contains entries from two different years, the React scheduler encounters an issue where it overlays the data incorrectly.
![image](https://github.com/Bitnoise/react-scheduler/assets/36660448/97ffbf79-faa2-45ea-8398-59e2a22ba122)

For example, consider the sample data provided below:

```javascript
data: [
  {
    id: "1",
    startDate: new Date("2023-03-11T08:00:00.000Z"),
    endDate: new Date("2023-08-11T08:00:00.000Z"),
    occupancy: 3600,
    title: "Test 2023",
    description: "2023",
    bgColor: "rgb(254,165,177)"
  },
  {
    id: "2",
    startDate: new Date("2024-03-18T08:00:00.000Z"),
    endDate: new Date("2024-03-24T15:59:59.649Z"),
    occupancy: 3600,
    title: "Test 2024",
    description: "2024",
    bgColor: "rgb(137, 207, 240)"
  }
]
```

In this scenario, the data with ID 1, representing the year 2023, should not appear because it's from the previous year. However, it is still being displayed.

My proposed solution is to add a condition in the `Tile.tsx` file. Specifically, when the width of the tile is greater than 0, we should only display the tile:

```javascript
// Existing code...

return (
  <div>
    {width > 0 && (
      // Existing tile rendering code...
    )}
  </div>
);
```

This adjustment ensures that only tiles with a valid width are displayed, effectively resolving the issue of overlaying data from different years.
![image](https://github.com/Bitnoise/react-scheduler/assets/36660448/a1df9679-3385-41a7-a169-207c328d2ad4)

**Comment by mGasiorek998** [comment]
Hi, we've push a new Scheduler version that contains fix for overlapping events.
Please update the package to the newest version - 0.3 and let us know if it helped :D
