### ISSUE TITLE
How to customise the events? or data visually?

### ISSUE THREAD

**Issue by appusvivek** [Bitnoise/react-scheduler#51]
How to customise the events? or data visually?

Any way we can modify them?

**Comment by mGasiorek998** [comment]
Hi @appusvivek 
As of today you can only customize the tile background color by providing bgColor property in your SchedulerData e.g
```ts 
 data: [{
      id: "8b71a8a5-33dd-4fc8-9caa-b4a584ba3762",
      startDate: new Date("2023-04-13T15:31:24.272Z"),
      endDate: new Date("2023-08-28T10:28:22.649Z"),
      occupancy: 3600,
      title: "Project A",
      subtitle: "Subtitle A",
      description: "array indexing Salad West Account",
      bgColor: "rgb(254,165,177)"
  }],
```
in this example tile will have light pink color

Any further visual customizations are planned to be implemented in the next version, so stay tuned!
