### ISSUE TITLE
"npm install @bitnoi.se/react-scheduler" installation

### ISSUE THREAD

**Issue by rupaligopalpatil** [Bitnoise/react-scheduler#55]
Hi,

I am not able to install this command, there is error while installing.
![image](https://github.com/Bitnoise/react-scheduler/assets/144344445/6e55699b-4e21-4b26-a31a-ba3532e96873)

So anyone help me in that.....

Thanks!!

**Comment by mGasiorek998** [comment]
Hi @rupaligopalpatil 

Please try installing it like so:
```bash
npm install "@bitnoi.se/react-scheduler"
```

Let us know if it helped you!

**Comment by rupaligopalpatil** [comment]
Yes Thanks a lot...!
