### ISSUE TITLE
New event create on click from frontend.

### ISSUE THREAD

**Issue by rupaligopalpatil** [Bitnoise/react-scheduler#56]
Hi,

Is there any way to add event on click of frontend instead of data provide from code.
Please share me if knows about it.

Thanks

**Comment by mGasiorek998** [comment]
Hi @rupaligopalpatil 

Scheduler has an event for clicking a given tile `onTileClick` and event for clicking a given item on left column `onItemClick`.

If it's something else that you want to do, please provide a code example of what you trying to achieve. It will help me better understand the issue you've been having.
