### ISSUE TITLE
Npm link is broken.

### ISSUE THREAD

**Issue by Goelcuek** [Bitnoise/react-scheduler#57]
npm install link doesn't work, throws "

At line:1 char:13
 npm install @bitnoi.se/react-scheduler

The splatting operator '@' cannot be used to reference variables in an expression. '@bitnoi' can be used only as an argument   
to a command. To reference variables in an expression use '$bitnoi'.
     CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
     FullyQualifiedErrorId : SplattingNotPermitted
"
error with powershell.

**Comment by mGasiorek998** [comment]
Hi @Goelcuek 

Please try installing it like so:
```bash
npm install "@bitnoi.se/react-scheduler"
```

Let us know if it helped you!
