### ISSUE TITLE
How to hide or update Free and Taken Hours?

### ISSUE THREAD

**Issue by JonoSuave** [Bitnoise/react-scheduler#63]
If a resource (in the screenshot example it's F-150 Truck) has more than one task on a project it doesn't appear that the amount of free and taken time for the day is accounted for between multiple tasks. Is there a way to only display the Taken hours only when hovering over a task?
<img width="759" alt="Screenshot 2023-12-06 at 7 19 09 AM" src="https://github.com/Bitnoise/react-scheduler/assets/22969971/1eff4dbc-b0b2-4480-8fb5-89ff11c9a213">

**Comment by mGasiorek998** [comment]
Hi @JonoSuave ,
it is a good idea for the feature!
We'll try to implement it in the next scheduler version.
If you can, please provide a detailed description how you think it should behave.

**Comment by jennylihan** [comment]
Relatedly, is it possible to customize the tooltip at all right now? Currently the tooltip text is not relevant to my gantt chart and I'd prefer to remove the tooltip entirely for now.

**Comment by mGasiorek998** [comment]
Unfortunately no, it's impossible to nether customize it nbor hiding it. But we will add the ability to remove it to the list of features to add in the future :)

**Comment by ludakhris** [comment]
+1
