### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Steveb599** [Bitnoise/react-scheduler#65]
Hi
Do you plan on making the calendar responsive and mobile-friendly in the future?
if so, how long do you think it would take?
Thank you

**Comment by lroth** [comment]
Hi!

We are considering making the scheduler mobile-friendly. However, due to its panoramic/horizontal view, we aim to make it not only responsive but also user-friendly. It is on our list, but there is no specific deadline, making it challenging to provide a timeframe.
