### ISSUE TITLE
Can items be grouped?

### ISSUE THREAD

**Issue by ycymycym** [Bitnoise/react-scheduler#68]
1.Can items be grouped? Can show or not show the data of this group,
2.How to hidden the tooltip or customize it？
3.Can you add a onEmptyClick  event?

**Comment by mGasiorek998** [comment]
Hi @ycymycym 
1. I don't know what do you mean by grouping data, scheduler allows to show multiple resources (tiles) per one item (row)
2. As of now it's impossible to hide it or customize it.
3. We have it planned for the next release :)
