### ISSUE TITLE
 more zoom in on the activity canvas

### ISSUE THREAD

**Issue by Rakuen2403** [Bitnoise/react-scheduler#70]
HI!
first I want to thank you for this development, I use your component in nextjs and I wonder if there is a possibility that at the zoom level it takes weeks, days and hours, this is because I have some activities where the work time is less than one day.

**Comment by mGasiorek998** [comment]
Hi @Rakuen2403 
glad you find our component useful :).
We are planning to add another zoom level for hours view in the next release.

**Comment by roggenbrot** [comment]
First also thx for this amazing component. 

When do you think the next version with hour zooming will released?  I'm asking because I was thinking of creating a PR for this feature, but if you already implemented it  I guess there's no need for this extra work.

**Comment by mGasiorek998** [comment]
We're just starting to work on the new release so I you have something figured out already we will be more than happy to look into it! :)

**Comment by elouafi** [comment]
@mGasiorek998 Hello, is there any updates please when this hours zoom level will be available?
Thanks

**Comment by domme1908** [comment]
Hi @mGasiorek998, are there any updates on this feature?
