### ISSUE TITLE
change the locale

### ISSUE THREAD

**Issue by Galhion** [Bitnoise/react-scheduler#72]
Hi, it's possible to change the locale of the scheduler in other languages with code?
Thanks!!!

**Comment by mGasiorek998** [comment]
Hi @Galhion 
as of now we only support polish (pl) and english (en).
You can change the locale in config object passed as prop to scheduler:
```ts
<Scheduler config={{ lang: 'en' }} />
```

**Comment by thomasrehm** [comment]
hi @mGasiorek998, what about merging the two open PRs #71 and #67 ?

**Comment by rossanodr** [comment]
> Hi @Galhion as of now we only support polish (pl) and english (en). You can change the locale in config object passed as prop to scheduler:
> 
> ```ts
> <Scheduler config={{ lang: 'en' }} />
> ```

Can you accept the pull requests of translations please?

**Comment by Galhion** [comment]
Sorry, my idea, for example, is a translation.js file in which you can put the translations of the different sections without having to open different branches, something like this:
```
lang:{ 'en' :{ 'monday': 'monday',....},
'es':{monday:'lunes',......},
'fr':{......}
}

```

**Comment by mGasiorek998** [comment]
Hi @Galhion 
It's a good idea.
We will try to implement something like this in the next release.

Thanks!
