### ISSUE TITLE
Module not found in react

### ISSUE THREAD

**Issue by amihudcohen** [Bitnoise/react-scheduler#74]
hello
After install on react 17 , js web app
Module not found: Can't resolve '@bitnoi.se/react-scheduler'

Checked and the module installed

Thank you

**Comment by BartoszBBitnoise** [comment]
Hello! 
Can you share your package.json and file where you use react-scheduler ?

**Comment by brnonm** [comment]
Hi!
I have the same problem, have any solutions?

In page i used react-scheduler when i import "import { Scheduler, SchedulerData } from "@bitnoi.se/react-scheduler";" compliter return this error
"./src/app/views/RH/sharedBooking/ManageBooking.jsx
Module not found: Can't resolve '@bitnoi.se/react-scheduler' in '-----------\RH\sharedBooking'"

My package.json
[package.json](https://github.com/Bitnoise/react-scheduler/files/14298991/package.json)

Thank you

**Comment by knapeto** [comment]
I have the same problem, guys! `Module not found: Can't resolve `..
