### ISSUE TITLE
How can I disable occupancy tooltips/titles that are shown on  every cell hover?

### ISSUE THREAD

**Issue by semeniuv** [Bitnoise/react-scheduler#75]
Can the occupancy also be an optional field?

**Comment by BartoszBBitnoise** [comment]
Hello! 
We are going to make this field optional as soon as the next release arrives

**Comment by kmocorro** [comment]
Hello - Thank you for making this library. I just want to know if this is still on going development? Thanks!

**Comment by mGasiorek998** [comment]
Yes, we've gathered some cool features ideas from the users so we're starting to work on the new release :)
