### ISSUE TITLE
window is not defined on NextJS 14

### ISSUE THREAD

**Issue by rossanodr** [Bitnoise/react-scheduler#76]
⨯ node_modules\@bitnoi.se\react-scheduler\dist\index.js (2034:35) @ window
 ⨯ Internal error: ReferenceError: window is not defined

"use client";
import { Scheduler, SchedulerProps } from "@bitnoi.se/react-scheduler";
import "@bitnoi.se/react-scheduler/dist/style.css";

export default function SchedulerClient(props: SchedulerProps) {
    return <Scheduler {...props} />;
}

**Comment by BartoszBBitnoise** [comment]
Hello! Please check this out if does it work when you change your Scheduler import into
```
const Scheduler = dynamic(
  () => import("@bitnoi.se/react-scheduler").then((mod) => mod.Scheduler),
  {
    ssr: false,
  }
);

```

**Comment by Pragmapic** [comment]
> Hello! Please check this out if does it work when you change your Scheduler import into
> 
> ```
> const Scheduler = dynamic(
>   () => import("@bitnoi.se/react-scheduler").then((mod) => mod.Scheduler),
>   {
>     ssr: false,
>   }
> );
> ```

Thanks @BartoszBBitnoise it does work.
The problem is the Scheduler is trying to render from server rendering and that's why he don't find window reference.
an other way to fix this is to wait to be in client side.
For this I just add a useEffect who only can be use from client side before rendering the component.
I hope it can also help, and I hope the problem will be fix soon :)

```tsx
export function GanttScheduler() {
  const [filterButtonState, setFilterButtonState] = useState(0);

  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  if (!isClient) return null;
  return (
    <div className="relative w-full h-[80vh] ">
      <Scheduler
        data={mockedSchedulerData}
        isLoading={false}
        onRangeChange={(newRange) => console.log(newRange)}
        onTileClick={(clickedResource) => console.log(clickedResource)}
        onItemClick={(item) => console.log(item)}
        onFilterData={() => {
          // Some filtering logic...
          setFilterButtonState(1);
        }}
        onClearFilterData={() => {
          // Some clearing filters logic...
          setFilterButtonState(0);
        }}
        config={{
          zoom: 0,
          filterButtonState,
        }}
      />
    </div>
  );
}
```
