### ISSUE TITLE
Not showing overlapping events

### ISSUE THREAD

**Issue by semeniuv** [Bitnoise/react-scheduler#78]
If there is a big event in the scheduler and if we add another one that overlaps with it, the second event is only shown if they have the same start date, but if a new small event has a start date at least one day after the old event start date it won't be shown at all.  This is quite an inconvenient issue as it is required to be able to show all events including those that overlap. I hope this issue will be fixed in some future release. Thanks.

**Comment by ludakhris** [comment]
+1

**Comment by mGasiorek998** [comment]
Hi @semeniuv 

I wasn't able to reproduce it. 
Can you please provide steps to reproduce or an image with the bug? It would be easier for us to debug it.

**Comment by semeniuv** [comment]
Hi @mGasiorek998,

It is a kinda strange issue as I faced it a few times and now cannot reproduce it either. I'll get back to you once I can reproduce it. Thanks for being so responsive.

**Comment by semeniuv** [comment]
I just noticed that it mostly happens on smaller screens. ON a big one it can be fixed by changing zoom from 1 to 0 and back to 1, but on smaller screens, it doesn't work.
