### ISSUE TITLE
Chaotic scrolling when the bottom scroll bar in the left end of the page 

### ISSUE THREAD

**Issue by semeniuv** [Bitnoise/react-scheduler#79]
When you put the bottom scroll bar to the left end the whole calendar begins to chaotically scroll until you move it slightly to the right or press the "Today" button

**Comment by semeniuv** [comment]
I am attaching a short screen recording. I hope it helps. It might be only my case, but who knows.

https://github.com/Bitnoise/react-scheduler/assets/72941109/c6a719a5-27d9-4193-a5a9-69c80ac839c8

**Comment by semeniuv** [comment]
Hi there. I've made a screen capture for you. It might only be my case though, but who knows maybe someone else also faced it. 
Please let me know if you need anything else from me. BTW, it's a great piece of software. 

https://github.com/Bitnoise/react-scheduler/assets/72941109/5d67c736-5585-4636-9fa7-1a1de03b7579

**Comment by mGasiorek998** [comment]
Can you please also provide what browser are you using?

**Comment by semeniuv** [comment]
> Can you please also provide what browser are you using?

Sure, it's Firefox.

**Comment by ibr-ibcs** [comment]
I use it in Chrome and face the same issue.

**Comment by ibr-ibcs** [comment]
@mGasiorek998 Is there any practical work-around for this issue? I noticed it happens even if the data is small and I casually scroll across the scheduler. 
As a side note, the node version I am using is 16.16.0 but I did not notice any apparent effects of using old version on the functionality of the `< Scheduler />`

**Comment by mGasiorek998** [comment]
Hi,
sorry for the late response, we've pushed a new scheduler version that should fix this issue.
Can you please check and let us know if it works for you now? :D

**Comment by adalbertopc** [comment]
hello! i have the same issue 
@mGasiorek998 i dont see the new version 😳

**Comment by adalbertopc** [comment]
@mGasiorek998 hello!
how can i use this branch as the library version?

because this v0.3 realease is not on the npm website 

https://github.com/Bitnoise/react-scheduler/tree/release/v0.3

**Comment by AdityaYInamdar** [comment]
Please update this on npm, I am having the same issue

**Comment by arek-bitnoise** [comment]
@AdityaYInamdar it was updated on npm. You can check it now.

**Comment by semeniuv** [comment]
This seems to be working fine now
