### ISSUE TITLE
Zoom Option for Months

### ISSUE THREAD

**Issue by ludakhris** [Bitnoise/react-scheduler#83]
Hi,

Kudos to you all for such an awesome and visually appealing component! I have a request very similar to #70.

I use this timeline to actually cover projects which very often take months. So it would be really useful to have a zoom option that was "months" or -1 if following the convention you all have in place.

**Comment by mGasiorek998** [comment]
Hi @ludakhris 
We're planning on expanding the zoom possibilities in the next release.
