### ISSUE TITLE
Documentation Error: Incorrect Scheduler Data

### ISSUE THREAD

**Issue by ludakhris** [Bitnoise/react-scheduler#84]
The scheduler data documentation seems to be incorrect here: https://github.com/Bitnoise/react-scheduler?tab=readme-ov-file#scheduler-data 

The page lists: id, data, and label (as a string). 

However the example on the webpage shows that label is a complex option with properties: icon, title, subtitle.

```
{
    id: "070ac5b5-8369-4cd2-8ba2-0a209130cc60",
    label: {
      icon: "https://picsum.photos/24",
      title: "Joe Doe",
      subtitle: "Frontend Developer"
    },
```

**Comment by mGasiorek998** [comment]
Hi @ludakhris 
Good catch! We will update the readme

**Comment by mGasiorek998** [comment]
Hi @ludakhris 
Readme was updated. Thanks!
