### ISSUE TITLE
Scheduler component takes over entire page

### ISSUE THREAD

**Issue by dishmael** [Bitnoise/react-scheduler#87]
I cannot seem to figure out how to use the scheduler in a page without the scheduler taking over the entire view.

**Comment by semeniuv** [comment]
I managed it by adding div wrapper with the following CSS styles:
 .scheduler-wrapper {
  position: relative;
  width: 100%;
  height: 60vh;
}

**Comment by dishmael** [comment]
@semeniuv thank you so much - I couldn't figure out the right CSS. I added your style and it's working perfectly. :)

**Comment by semeniuv** [comment]
Happy to help
