### ISSUE TITLE
Different views in calendar

### ISSUE THREAD

**Issue by pagusek** [Bitnoise/react-scheduler#90]
Dear Bitnoise,

first of all I'd like to tell that your scheduler looks very modern in comparison to currently available components. Great job.

I've got two questions:
1. When you estmiate to deliver drag&drop and mentioned features? 
2. Currently as far as I can see you support only view, where hours are on top and resources on left. Do you plan to have standard day/week/month view (hours on left and for example Monday, Tuesday, etc on top.)?

**Comment by mGasiorek998** [comment]
Hi @pagusek 
glad you enjoy our component :)

We're starting the works on new scheduler release, but it's early stage and we don't have yet estimates for how long it may take to finish it.

**Comment by mGasiorek998** [comment]
We do plan to add months view as well as days view, but the layout will remain the same - list of resources on the left column and timeline on the top :)

**Comment by gap579137** [comment]
Any update on this? JW

**Comment by mGasiorek998** [comment]
We're are working on in and we should release a new scheduler version with days view

**Comment by arek-bitnoise** [comment]
Hourly view was released in version 0.3.0. Use `zoom=2` to use it.
Drag n drop is on our list of new features that we want to investigate.
