### ISSUE TITLE
I18n for FR

### ISSUE THREAD

**Issue by lau-sam** [Bitnoise/react-scheduler#99]
Add French translations. Currently only English and Polish are supported.

**Comment by lau-sam** [comment]
Hi, I made a PR about this issue here : https://github.com/Bitnoise/react-scheduler/pull/100

Could you please review and give me feedback if necessary?

**Comment by KhalidBls** [comment]
+1

**Comment by lau-sam** [comment]
@KhalidBls We forked and published a version that supports the French language. It's just temporary until the Bitnoise team responds to find out if they're continuing to maintain it or not. It's been a while since they've replied to the various issues, and I've even sent an unanswered e-mail. 

If they continue to maintain this package, we'll be happy to continue contributing to this wonderful package created by Bitnoise.

The link : https://www.npmjs.com/package/@coderkaine/react-scheduler

**Comment by KhalidBls** [comment]
@lau-sam Oh thanks a lot ! <3
